# permissions for end users to edit wasmcloudhostconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: k8s-wasmcloudhostconfig-editor-role
rules:
- apiGroups:
  - k8s.wasmcloud.dev
  resources:
  - wasmcloudhostconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.wasmcloud.dev
  resources:
  - wasmcloudhostconfigs/status
  verbs:
  - get
