# permissions for end users to view applications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: oam-application-viewer-role
rules:
  - apiGroups:
      - core.oam.dev
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - core.oam.dev
    resources:
      - applications/status
    verbs:
      - get
